services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    command:
      [
        './wait-for-connect.sh',
        'db:5432',
        '--',
        'python',
        'manage.py',
        'runserver',
        '0.0.0.0:8000',
      ]

  web:
    build: ./frontend
    ports:
      - '3000:80'
    volumes:
      - ./frontend:/frontend
