services:
  api:
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/backend

  web:
    build: ./frontend
    ports:
      - '3000:80'
    volumes:
      - ./frontend:/frontend
