services:
  api:
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/backend
    depends_on:
      - db

  web:
    build: ./frontend
    ports:
      - '3000:80'
    volumes:
      - ./frontend:/frontend

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
